### ISSUE TITLE
Setting a menu ("", description) hides HeadTextures

### ISSUE THREAD

**Issue by manups4e** [TomGrobbe/MenuAPI#14]
if i create a menu like 
```
Menu MenuVariable = new Menu("", "this is a description");
MenuVariable.HeaderTexture = new KeyValuePair<string, string>("texture", "texture");
```
if the title is set to "" (empty) the HeaderTexture is hidden... to show the HeaderTexture i have to use an empty char (space bar key) like " "

**Comment by TomGrobbe** [comment]
Yeah, this is because by default if you have no title, it will only show the subtitle (if present). To allow you to create similar menus to like the GTA:O apartment entrance options menu.

Like you said, just put an empty character like a space, or something like `~s~` to make an empty title and still have the custom header be visible.

**Comment by manups4e** [comment]
Ooook i thought it could have been a big so I preferred to warn you

**Comment by TomGrobbe** [comment]
All good. :)
